services:
  disc_tracker:
    build: .
    container_name: disc-tracker_app
    restart: always
    depends_on:
      - db

    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: disc-tracker_db
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: disc-tracker_nginx
    restart: always
    depends_on:
      - disc_tracker
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


volumes:
  pg_data: