
services:
  disc_tracker:
    image: ${DOCKER_IMAGE}
    container_name: disc-tracker_app
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: disc-tracker_db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: disc-tracker_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - disc_tracker

  test:
    image: ${DOCKER_IMAGE}
    container_name: disc-tracker_tests
    depends_on:
      - disc_tracker
      - db
    env_file: .env
    command: ["/app/scripts/wait-for-it.sh", "db:5432", "--", "python", "manage.py", "test", "tests.integration"] 
    volumes:
      - .:/app
    restart: "no"