
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: disc-tracker_app
    restart: always
    env_file: 
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    container_name: disc-tracker_db
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    volumes: 
      - pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    
  redis:
    container_name: disc-tracker_redis
    restart: always
    image: redis:latest
    ports:
      - '6379:6379' 

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: disc-tracker_celery
    restart: always
    env_file:
      - .env
    command: celery -A disctracker worker --loglevel=info
    depends_on:
      - redis
      - app
    volumes:
      - .:/app

volumes:
  pgdata: