# Generated by Django 5.1.5 on 2025-01-27 00:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cex_id', models.CharField(max_length=255)),
                ('sell_price', models.FloatField()),
                ('exchange_price', models.FloatField()),
                ('cash_price', models.FloatField()),
                ('last_checked', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.FloatField()),
                ('exchange_price', models.FloatField()),
                ('cash_price', models.FloatField()),
                ('date_checked', models.DateField(default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='items.item')),
            ],
        ),
    ]
