# Generated by Django 5.1.5 on 2025-03-03 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_alter_item_cash_price_alter_item_cex_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="last_checked",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="date_checked",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
