# Generated by Django 5.1.5 on 2025-03-06 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0005_remove_item_user_useritem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="cex_id",
            field=models.CharField(
                db_index=True,
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9]+$", "ID must be alphanumeric characters"
                    )
                ],
            ),
        ),
    ]
