# Generated by Django 5.1.5 on 2025-03-06 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0006_alter_item_cex_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useritem",
            index=models.Index(
                fields=["user", "item"], name="items_useri_user_id_df6d48_idx"
            ),
        ),
    ]
