# Generated by Django 5.1.5 on 2025-01-26 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_history',
        ),
    ]
