# Generated by Django 5.1.5 on 2025-01-26 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discs', '0002_no_price_history_fk_in_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='discs.item'),
        ),
    ]
