name: Django CI

on:
  push:
    branches: [ "feature/deployment-pipeline" ]
  pull_request:
    branches: [ "feature/deployment-pipeline" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DiscTracker
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test